### ISSUE TITLE
refactoring the repository: gambit_np & GLEDELi

### ISSUE THREAD

**Issue by fzeiser** [anderkve/gledeli#21]
As discussed via mail, I want to refactor this repository to two parts:
- GLEDELi
- gambit (np)

I think the most convenient version is that I extract the gledeli subfolder using [git-filter-repo](https://github.com/newren/git-filter-repo), and replace this repository there by the files from GLEDELi. Then we rename this repo to GLEDELi [-- this way we keep the issues]

In addition, we can set up a new repository, gambit_np[new]; which can be a for of gambit. The nuclear specific parts can be a new branch that is rebased on top of gambit/master. We can then include GLEDELi as a submodule to gambit_np.

When making gambit_np, we can *ditch*  the modules (BITs) we don't need, and/or have an additional script that helps us having to download & compile less data.  

I will of course keep a backup of this repository just in case

**Comment by fzeiser** [comment]
Working on including gledeli as a submodule. But sofar, it just takes for ages to download GAMBIT. I think it was a design mistake that GAMBIT doesn't include the BITS as submodules, but keeps it all in a very large repo. At least it can be inconvenient. I guess I should have a look into sparse-checkout.

**Comment by fzeiser** [comment]
Added it now. There is a slight change in the directory structure, see comment here https://github.com/anderkve/gambit_np/commit/819f686fff6f26d4cdf5cda82c4c039be059cb9a

**Comment by anderkve** [comment]
> Working on including gledeli as a submodule. But sofar, it just takes for ages to download GAMBIT. I think it was a design mistake that GAMBIT doesn't include the BITS as submodules, but keeps it all in a very large repo. 

Nah, I disagree. :) I think submodules are intended for codes that are more clearly independent than the various Bits of GAMBIT. There is a lot of development and physics work in GAMBIT that effectively involves making updates across many Bits, and that would be quite painful to work with as separate git repos. Also, cloning the GAMBIT repo is a one-off thing -- doesn't really matter if it takes a few minutes. (I just tested cloning the repo from scratch -- it's a ~500 MB download and for me takes ~30 seconds.) And those who simply want to use GAMBIT as is can always just download the tarball with the source that we provide, which is only 14 MB. 

Anyways, thanks for adding it!

**Comment by fzeiser** [comment]
>  There is a lot of development and physics work in GAMBIT that effectively involves making updates across many Bits

Ok, that's a very good point. I'll try to see about the sparse-checkout. It seems to be what I'd like for such a situation if I ever set up a testing suite.
